apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/istio/istio.git
    # targetRevision: {{ .Values.istio.revision }}
    targetRevision: "1.9.0"
    path: manifests/charts/istio-operator

  destination:
    namespace: istio-operator
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true