---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators: 
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'prometheus'
    spec:
      project: default

      source:
        path: charts/prometheus
        repoURL: https://github.com/BadLiveware/kubernetes-gitops.git
        targetRevision: HEAD
        helm:
          valueFiles:
          # Base common values
          - values.yaml
          # Environment specific specific
          - 'values-{{"{{cluster}}"}}.yaml'

      destination:
        server: '{{"{{url}}"}}'
        namespace: prometheus

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true


