apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    path: apps
    repoURL: https://github.com/BadLiveware/kubernetes-gitops.git
    targetRevision: HEAD

  destination:
    # server: {{ .Values.cluster }}
    server: "https://kubernetes.default.svc"
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
